server:
  port: 8081
  servlet:
    context-path: /demo
  thymeleaf:
    cache: true
    check-template: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_boot?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true
    name: lgc


mybatis:
  type-aliases-package: com.jasmine.pojo
  mapper-locations: classpath:mappers/*.xml



logging:
  config: classpath:logback-spring.xml
#  path: /Users/lgc/Desktop

#屏蔽包
#  logging:
#    level:
#      com.ly.logback.controller: 'off'
